/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import DAO.ContatoDAO;
import Modelo.Contato;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FuryX
 */
public class Listar extends javax.swing.JDialog {

    /**
     * Creates new form Listar
     */
    public Listar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listar();
    }
    String titulo[] = {"Codigo", "Nome", "Telefone", "Email", "Celular"};
    Object [][] dados;
    public void listar(){
        List<Contato> lista = new ContatoDAO().listar();
        int i=0;
        dados = new Object[lista.size()][5];
        for (Contato contato : lista){

            
            dados [i][0] = contato.getCodigo();
            dados [i][1] = contato.getNome();
            dados [i][2] = contato.getEmail();
            dados [i][3] = contato.getTel();
            dados [i][4] = contato.getCel();
            i++;
        }
        Tabela.setModel(new DefaultTableModel(dados, titulo));
        Rolagem.setViewportView(Tabela);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Listar = new javax.swing.JPanel();
        Rolagem = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Busca = new javax.swing.JPanel();
        LblNome = new javax.swing.JLabel();
        txtDigitar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        Botoes = new javax.swing.JPanel();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        Listar.setLayout(new java.awt.BorderLayout());

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Rolagem.setViewportView(Tabela);

        Listar.add(Rolagem, java.awt.BorderLayout.CENTER);

        LblNome.setText("Nome");
        Busca.add(LblNome);

        txtDigitar.setColumns(20);
        txtDigitar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDigitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarActionPerformed(evt);
            }
        });
        txtDigitar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDigitarKeyReleased(evt);
            }
        });
        Busca.add(txtDigitar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        Busca.add(btnBuscar);

        Listar.add(Busca, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(Listar, java.awt.BorderLayout.CENTER);

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        Botoes.add(btnIncluir);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        Botoes.add(btnAlterar);

        btnConsultar.setText("Consultar");
        Botoes.add(btnConsultar);

        btnExcluir.setText("Excluir");
        Botoes.add(btnExcluir);

        getContentPane().add(Botoes, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
                Inserir inserir = new Inserir(null, true);
                inserir.setVisible(true);
                listar();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
                int linha = Tabela.getSelectedRow();
                int codigo = Integer.parseInt(Tabela.getValueAt(linha, 0).toString());
                
                Contato c = new ContatoDAO().consultar(codigo);
                
                Alterar alterar = new Alterar(null, true);
                alterar.atualizaCampos(c);
                alterar.setVisible(true);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtDigitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarActionPerformed
        
    }//GEN-LAST:event_txtDigitarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtDigitarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDigitarKeyReleased

    }//GEN-LAST:event_txtDigitarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Listar dialog = new Listar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botoes;
    private javax.swing.JPanel Busca;
    private javax.swing.JLabel LblNome;
    private javax.swing.JPanel Listar;
    private javax.swing.JScrollPane Rolagem;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JTextField txtDigitar;
    // End of variables declaration//GEN-END:variables
}
